In [1]:
!Pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,4])
b=np.array([2,7,9])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[ 3  9 13]
[-1 -5 -5]
[ 2 14 36]
[0.5        0.28571429 0.44444444]
[0 0 0]


In [4]:
a=np.array([[5,4,9],[9,4,7],[5,2,8]])
b=np.array([[2,4,6],[9,8,7],[3,2,6]])
np.dot(a,b)

array([[ 73,  70, 112],
       [ 75,  82, 124],
       [ 52,  52,  92]])

In [5]:
a=np.array([[5,4,9],[9,4,7],[5,2,8]])
np.transpose(a)

array([[5, 9, 5],
       [4, 4, 2],
       [9, 7, 8]])

In [6]:
a=np.array([[5,4,9],[9,4,7],[5,2,8]])
b=np.array([[2,4,6],[9,8,7],[3,2,6]])
np.concatenate([a,b])

array([[5, 4, 9],
       [9, 4, 7],
       [5, 2, 8],
       [2, 4, 6],
       [9, 8, 7],
       [3, 2, 6]])